# Application Configuration
spring.application.name=order-service

# Server Configuration
server.port=8081
server.servlet.context-path=/api
inventory.service.url=http://localhost:8080/api


# Database Configuration
spring.datasource.url=jdbc:postgresql://localhost:5432/order_db
spring.datasource.username=postgres
spring.datasource.password=410920
spring.datasource.driver-class-name=org.postgresql.Driver


# JPA/Hibernate Configuration
spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=false


# JWT Configuration
spring.security.oauth2.resourceserver.jwt.issuer-uri=http://localhost:9090/realms/ecommerce-realm
jwt.expiration=86400000




# Adresse du serveur Kafka (Broker)
spring.kafka.bootstrap-servers=${KAFKA_SERVERS:localhost:9092}

# Configuration du Producer
spring.kafka.producer.key-serializer=org.apache.kafka.common.serialization.StringSerializer
spring.kafka.producer.value-serializer=org.springframework.kafka.support.serializer.JsonSerializer
spring.kafka.producer.properties.spring.json.add.type.headers=false



logging.level.org.springframework.security=DEBUG
logging.level.org.springframework.web=DEBUG


